<a href="https://colab.research.google.com/github/Swati642/Python-Assignment-1/blob/main/Copy_of_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?
Ans. NumPy is a powerful library in Python designed for scientific computing and data analysis. Its main purpose is to provide efficient array manipulation and numerical operations. Key advantages include:

Efficient Multidimensional Arrays: NumPy introduces the ndarray object, a highly efficient, fixed-size, and homogeneous data structure for storing large datasets.

Performance: It is much faster than regular Python lists due to optimized C and Fortran code under the hood, enabling vectorized operations and parallel computation.

Mathematical Functions: NumPy offers a vast collection of built-in functions for operations like linear algebra, statistics, and Fourier transforms, enhancing Python's ability for complex calculations.

Memory Efficiency: NumPy arrays use less memory compared to lists and can handle large datasets more effectively.

Interoperability: It integrates seamlessly with other scientific libraries (e.g., SciPy, pandas, Matplotlib), enhancing Python's utility for data analysis and scientific research.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?
Ans. In NumPy, both np.mean() and np.average() are used to compute the average of an array, but they have distinct differences:

np.mean():
Purpose: Computes the arithmetic mean (average) of an array or along a specified axis.
Usage: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
Default behavior: It simply sums the elements of the array and divides by the total number of elements.
No weighting: It assumes equal weights for all elements.
np.average():
Purpose: Computes a weighted average of an array, with the option to apply different weights to different elements.
Usage: np.average(a, axis=None, weights=None, returned=False)
Default behavior: When no weights are specified, it behaves like np.mean(). However, it allows the user to specify weights, enabling the calculation of a weighted average.
Weighted averaging: If weights are provided, each element is multiplied by its corresponding weight before averaging.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.
Ans. 1D Array Reversal:
Use slicing ([::-1]) or np.flip() to reverse a 1D array.
2D Array Reversal:
Use np.flip(arr_2d, axis=0) to reverse along rows (up-down).
Use np.flip(arr_2d, axis=1) to reverse along columns (left-right).
Use np.flipud() for up-down reversal (rows).
Use np.fliplr() for left-right reversal (columns).

In [ ]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = np.flip(arr_1d)
print(reversed_arr_1d)

[5 4 3 2 1]


In [ ]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse along rows (axis=1)
reversed_rows = np.flip(arr_2d, axis=0)
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.
Ans. to determine Data Type in NumPy, dtype attribute is used

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)

Importance of Data Types in Memory and Performance
Memory Efficiency: Smaller data types (e.g., int8, float32) consume less memory, enabling handling larger datasets.
Performance: Smaller data types lead to faster computations, better cache utilization, and reduced memory access time.
Overflow: Choosing an appropriate data type avoids overflow and errors (e.g., int8 for values larger than 127 will overflow).
Type Conversion: You can convert data types using astype() to optimize memory or ensure compatibility.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
Ans. An ndarray (n-dimensional array) is the core data structure in NumPy. It is a grid of values, all of the same data type, indexed by a tuple of non-negative integers. It is used for efficient storage and manipulation of large datasets.
Key Features of ndarrays:
Homogeneous Data: All elements in an ndarray are of the same type (e.g., integers, floats).
Multidimensional: ndarrays can be one-dimensional (1D), two-dimensional (2D), or more, supporting n-dimensional data structures.
Fixed Size: Once created, the size of an ndarray cannot be changed. However, reshaping can create a new array with different dimensions.
Efficient Memory Layout: ndarrays are stored in contiguous memory locations, allowing for faster access and operations compared to Python lists.
Vectorized Operations: You can perform element-wise operations on entire arrays, avoiding Python loops and significantly improving performance.
Differences Between ndarrays and Python Lists:
Homogeneity:

ndarrays: All elements must be of the same type.
Python Lists: Can store elements of different types.
Performance:

ndarrays: More memory-efficient and faster for numerical operations due to fixed data type and contiguous memory storage.
Python Lists: Slower for numerical computations due to flexibility in data types and non-contiguous memory storage.
Functionality:

ndarrays: Support advanced operations like slicing, broadcasting, and vectorized arithmetic.
Python Lists: Lack support for such operations, requiring manual iteration or external libraries.

In [ ]:
#example -
import numpy as np

# Creating a 1D ndarray
arr = np.array([1, 2, 3, 4])
print(arr)  # Output: [1 2 3 4]

# Creating a 2D ndarray
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)  # Output: [[1 2]
               #          [3 4]]

# Python list
py_list = [1, 2, 3, 4]
print(py_list)  # Output: [1, 2, 3, 4]

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
Ans.
Performance Benefits of NumPy Arrays Over Python Lists
Memory Efficiency:

NumPy: Stores elements in contiguous memory, reducing overhead.
Python lists: Store elements as pointers, leading to more memory usage.
Faster Computations:

NumPy: Uses optimized C/Fortran libraries, supports vectorized operations (element-wise on entire arrays).
Python lists: Requires manual iteration, slower for large data.
Broadcasting:

NumPy: Supports broadcasting for operations on arrays of different shapes.
Python lists: No native broadcasting, requires custom loops.
Multithreading:

NumPy: Optimized for multi-threading and parallelism in large datasets.
Python lists: No built-in parallelism.
Vectorization:

NumPy: Supports vectorized operations, faster computation.


In [ ]:
#example
import numpy as np
import time

# Python list sum
py_list = [i for i in range(10**6)]
start = time.time()
sum(py_list)
end = time.time()
print(f"Python list sum time: {end - start}")

# NumPy array sum
np_array = np.array([i for i in range(10**6)])
start = time.time()
np.sum(np_array)
end = time.time()
print(f"NumPy array sum time: {end - start}")

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.
Ans. Comparison of vstack() and hstack() in NumPy
vstack(): Stacks arrays vertically (row-wise).
hstack(): Stacks arrays horizontally (column-wise).
Usage:
vstack(): Stacks arrays on top of each other (along the first axis).

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_vstack = np.vstack((arr1, arr2))
print(result_vstack)

hstack(): Stacks arrays side by side (along the second axis).

In [ ]:
result_hstack = np.hstack((arr1, arr2))
print(result_hstack)

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.
Ans fliplr() (Flip Left-Right):

Effect: Reverses the elements of an array horizontally (left to right), i.e., along the second axis (axis=1).
Use case: Used to reverse the columns of an array.
Example:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_lr = np.fliplr(arr)
print(flipped_lr)

flipud() (Flip Up-Down):

Effect: Reverses the elements of an array vertically (top to bottom), i.e., along the first axis (axis=0).
Use case: Used to reverse the rows of an array.

In [ ]:
flipped_ud = np.flipud(arr)
print(flipped_ud)

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
Ans. The array_split() method in NumPy is used to split an array into multiple sub-arrays. It allows for splitting arrays along a specified axis into a specified number of parts.

Functionality:
Syntax: np.array_split(array, indices_or_sections, axis=0)
array: The input NumPy array to split.
indices_or_sections: Number of splits or an array of indices where splits should occur.
axis: The axis along which to split (default is 0).
Handling Uneven Splits:
When the array cannot be evenly divided into the specified number of sections, NumPy distributes the remaining elements across the first few sub-arrays.
For example, if you try to split an array with 10 elements into 3 parts, the first two parts will contain 4 elements, and the third will contain 2 elements.

In [ ]:
#Even split
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, 3)
print(result)

In [ ]:
#uneven split
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = np.array_split(arr, 4)
print(result)

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?
Ans. Vectorization refers to the process of performing operations on entire arrays without using explicit loops. NumPy allows you to apply mathematical operations (like addition, multiplication, etc.) directly to whole arrays, and it automatically handles the element-wise computations behind the scenes.

Benefits:
Faster Execution: Operations are executed in compiled C code, making them faster than Python loops.
Cleaner Code: No need for loops, making the code more concise and easier to read.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
result = arr * 2  # Element-wise multiplication
print(result)

Broadcasting is a technique that allows NumPy to perform operations on arrays of different shapes. When performing operations between arrays of different sizes, NumPy automatically "broadcasts" the smaller array to match the shape of the larger array, without explicitly replicating data.

Rules:
The dimensions of the arrays must be compatible.
The smaller array is broadcasted to match the shape of the larger one.

In [ ]:
arr1 = np.array([1, 2, 3])       # Shape: (3,)
arr2 = np.array([10])             # Shape: (1,)
result = arr1 + arr2              # Broadcasting occurs
print(result)

Efficiency Benefits:
Faster Execution: Vectorized operations are highly optimized and run much faster than Python loops.
Memory Efficiency: Broadcasting avoids the need to replicate data, which reduces memory overhead.
Concise Code: Both vectorization and broadcasting make it easier to write and maintain code for array operations.

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [ ]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchange rows and columns (transpose the array)
arr_transposed = arr.T
print("\nTransposed Array:")
print(arr_transposed)

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [ ]:
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # This creates an array with elements from 0 to 9

# Step 2: Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Step 3: Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

# (Optional) Print the arrays to see the results
print("1D Array:\n", array_1d)
print("\nReshaped to 2x5 Array:\n", array_2x5)
print("\nReshaped again to 5x2 Array:\n", array_5x2)

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
import numpy as np

# Create a 4x4 array with random float values
original_array = np.random.rand(4, 4)

# Add a border of zeros around the original array
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:\n", original_array)
print("\n6x6 Array with Border of Zeros:\n", bordered_array)

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np

# Create the array
array = np.arange(10, 61, 5)

print(array)

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply different case transformations
upper_case = np.char.upper(arr)        # Uppercase
lower_case = np.char.lower(arr)        # Lowercase
title_case = np.char.title(arr)        # Title Case
capitalize = np.char.capitalize(arr)    # Capitalize

# Displaying the results
print("Original:", arr)
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title Case:", title_case)
print("Capitalize:", capitalize)

6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

print(spaced_words)

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
addition_result = arr1 + arr2

# Element-wise subtraction
subtraction_result = arr1 - arr2

# Element-wise multiplication
multiplication_result = arr1 * arr2

# Element-wise division
division_result = arr1 / arr2

addition_result, subtraction_result, multiplication_result, division_result

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements


In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

identity_matrix, diagonal_elements

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [ ]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, 100)

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Filter and display all prime numbers in the array
prime_numbers = arr[np.vectorize(is_prime)(arr)]

prime_numbers

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [ ]:
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(10, 30, 30)  # Random temperatures between 10 and 30 degrees

# Reshape the array into 4 weeks (7 days per week, leaving 2 days in the last week)
reshaped_temperatures = daily_temperatures.reshape(4, -1)

# Calculate the weekly averages
weekly_averages = reshaped_temperatures.mean(axis=1)

daily_temperatures, reshaped_temperatures, weekly_averages